### ISSUE TITLE
Cannot get bot online.

### ISSUE THREAD

**Issue by MrWizard516** [JamesIves/discord-wow-armory-bot#26]
Hello, I have setup as per your instructions and the bot shows up in my Discord members list but I cannot seem to get it to send any information. I am not sure what I am doing wrong. Please help! Thanks in advance.

**Comment by JamesIves** [comment]
@MrWizard516 Are you running this with Heroku? If so can you go to `Settings` and then click `Reveal Config Vars` within the application and then confirm that you have all of the environment variables setup as listed [here](https://github.com/JamesIves/discord-wow-armory-bot#configuration).

Without them the bot will not be able to come online as it requires a number of third party API keys. Keep in mind that the names are case sensitive, so they need to be all in blocked caps.

**Comment by JamesIves** [comment]
Did you get this figured out @MrWizard516 ?

**Comment by JamesIves** [comment]
Please re-open this issue if you're still having trouble.
