### ISSUE TITLE
Self host or integration with Red-DiscordBot

### ISSUE THREAD

**Issue by iCancerous** [JamesIves/discord-wow-armory-bot#31]
I would rather not host this off of Heroku or something, but rather load it into another bot, anyway to make this an add-on the the lovely Red-DiscordBot or self hosting?

**Comment by JamesIves** [comment]
You can self-host the bot on whatever service you choose, Heroku is just a suggestion because of the one-click install. Just download the code and run it wherever you like.

I'm unfamiliar with Red-DiscordBot, do you have a link?
