### ISSUE TITLE
No web processes running

### ISSUE THREAD

**Issue by Asurein** [JamesIves/discord-wow-armory-bot#35]
Hello i have an issu when i try to start the app on heroku, i'got this as error 

at=error code=H14 desc="No web processes running" method=GET path="/" host=alliancefr.herokuapp.com request_id=3c09b8e6-874f-434d-b455-2003d0203045 fwd="my ip" dyno= connect= service= status=503 bytes= protocol=https

i checked https://devcenter.heroku.com/articles/error-codes#h14-no-web-dynos-running

But i don't know what to do :/, could you help me please ?

**Comment by JamesIves** [comment]
Did you set this up with the one click installer option? I've never encountered this error before.
