### ISSUE TITLE
discord-wow-armory-bot broken by aiohttp and discord.py

### ISSUE THREAD

**Issue by NeolithEra** [JamesIves/discord-wow-armory-bot#65]
Hi, users are unable to run **_discord-wow-armory-bot_** due to dependency conflict with _**aiohttp**_ package. 
As shown in the following full dependency graph of **_discord-wow-armory-bot_**, discord-wow-armory-bot requires _**aiohttp==3.5.4**_，while **_discord.py==0.16.12_** requires _**aiohttp>=1.0.0,<1.1.0**_.

According to pip’s “first found wins” installation strategy, _**aiohttp==3.5.4**_ is the actually installed version. However, _**aiohttp==3.5.4**_ does not satisfy _**aiohttp>=1.0.0,<1.1.0**_.

### Dependency tree
```
discord-wow-armory-bot-4.0.5
| +-aiohttp(version range:==3.5.4)
| +-discord-py(version range:==0.16.12)
| | +-aiohttp(version range:>=1.0.0,<1.1.0)
| | +-websockets(version range:>=3.1,<4.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be aiohttp>=1.0.0,<1.1.0. I have checked this revision will not affect your downstream projects now.
2.	Upgrade discord.py to 1.2.3, as discord.py 1.2.3 requires aiohttp>=3.3.0,<3.6.0. 
Then this conflict can be removed.

Which solution do you prefer, 1 or 2?
@JamesIves Please let me know your choice. I can submit a PR to solve this issue.

**Comment by JamesIves** [comment]
@NeolithEra Thanks for the report! I think option 1 makes the most sense right now as there's some additional changes that are needed to make `1.2.3` work correctly. I have those changes in the works and hope to have them completed in time for the next tier.

**Comment by JamesIves** [comment]
This will be fixed as part of version 5.
